package com.vvu981.colivibackend.features.home.domain;

public enum ActivityType {
    HOME_CREATED,
    HOME_DELETED,
    MEMBER_JOINED,
    MEMBER_LEFT,
    MEMBER_EXPELLED,
    ADMIN_TRANSFERRED,
    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    EXPENSE_DELETED,
    PAYMENT_RECORDED,
    CHORE_SERIES_CREATED,
    CHORE_COMPLETED,
    CHORE_RESCUED,
    CHORE_DELETED
}
