spring.application.name=Colivi-backend

# 86400000 ms = 24 horas para el token normal
jwt.expiration=86400000
# 604800000 ms = 7 días para el refresh token
jwt.refresh-expiration=604800000
# Una clave secreta MUY larga (mínimo 256 bits)
jwt.secret=EstaEsUnaClaveSecretaMuyLargaYComplejaParaElTFGDeVictorVallejoColivi2024