name: Backend Tests

on:
  push:
    branches: [ "main" ]
    # Solo se ejecuta si hay cambios dentro de la carpeta del backend
    paths:
      - 'colivi-backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'colivi-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./colivi-backend

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Ejecutar las pruebas
        run: mvn -B test